services:
  #app:
  #  build: .
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - db
  #  environment:
  #    PG_DB: shortener
  #    PG_USER: user
  #    PG_PASSWORD: password
  #    PG_HOST: db
  #    PG_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
      